export const experienceData = [
  {
    title: "Frontend Developer",
    company: "Vidyayatan Technologies",
    dates: "December 2024 - December 2025",
    description: "As a frontend developer:",
    responsibilities: [
      "Maintained and improved a Tenant Management web app with Next and Tailwind CSS.",
      "Drove 8–10% increase in tenant engagement across active users.",
      "Built and maintained mobile apps with Capacitor for App Store and PlayStore.",
      "Shipped 2 internal products to production.",
      "Supported launch of the company's LMS mobile app.",
      "Handled build, testing, and store submission across multiple release cycles.",
      "Improved onboarding flows for a Labour Management System (500+ users).",
      "Created admin dashboards and cut manual onboarding steps by 10–15%.",
      "Added analytics views, subscription tracking, and QR-based scanning.",
      "Supported QA to reduce recurring production issues by 10%.",
    ],
    responsibilitiesMobile: [
      "Tenant Management web app (React, Tailwind).",
      "8–10% higher tenant engagement.",
      "Mobile apps with Capacitor (App Store, PlayStore).",
      "Shipped 2 internal products.",
      "LMS mobile app launch and store submission.",
      "Onboarding flows for LMS (500+ users).",
      "Admin dashboards; 10–15% fewer manual steps.",
      "Analytics, subscriptions, QR scanning.",
      "QA support; 10% fewer production issues.",
    ],
    techStack: [
      "JavaScript",
      "Tailwind",
      "React",
      "NextJS",
      "Typescript",
      "Capacitor",
      "Xcode",
      "Android Studio",
    ],
  },
  {
    title: "Frontend Engineer",
    company: "Nexus",
    dates: "July 2024 - December 2025",
    description: "Working as a Frontend Engineer, focusing on user interfaces and IDEs.",
    responsibilities: [
      "Integrated backend endpoints with the frontend.",
      "Enhanced UX across the product.",
      "Developed new features for the IDE.",
      "Improved UI and user flows.",
    ],
    responsibilitiesMobile: [
      "Backend integration and frontend.",
      "UX improvements.",
      "New IDE features.",
      "UI and user flow improvements.",
    ],
    techStack: [
      "JavaScript",
      "Tailwind",
      "React",
      "Git",
      "Node",
      "AWS",
      "Figma",
    ],
  },
  {
    title: "Frontend Developer Intern",
    company: "Judix",
    dates: "July 2024 - July 2024",
    description: "Focused on UI development and component building.",
    responsibilities: [
      "Built responsive UI components with React and Tailwind.",
      "Worked with designers for brand consistency.",
      "Optimized pages for faster mobile load times.",
    ],
    responsibilitiesMobile: [
      "Responsive UI (React, Tailwind).",
      "Design collaboration, brand consistency.",
      "Faster mobile load times.",
    ],
    techStack: ["JavaScript", "Tailwind", "React", "NextJS"],
  },
  {
    title: "Web Developer Intern",
    company: "JoinDevOps",
    dates: "March 2024 - May 2024",
    description: "As a web developer intern:",
    responsibilities: [
      "Managed website updates and automation.",
      "Helped launch the new company website.",
      "Implemented geolocation tagging with JavaScript.",
      "Added DOM manipulation and other front-end features.",
    ],
    responsibilitiesMobile: [
      "Site updates and automation.",
      "New company website launch.",
      "Geolocation and DOM work (JS).",
    ],
    techStack: ["HTML", "CSS", "JavaScript", "Webflow"],
  },
  {
    title: "UI/UX Designer",
    company: "Freelance",
    dates: "September 2023",
    description: "As a freelance UI/UX designer:",
    responsibilities: [
      "Designed a crypto landing page with clear visuals and navigation.",
      "Implemented visual elements and content layout for a crypto news site.",
      "Optimized UX to encourage exploration and engagement.",
      "Built a responsive layout for all devices.",
      "Delivered a polished intro experience for the platform.",
    ],
    responsibilitiesMobile: [
      "Crypto landing page (visuals, nav).",
      "Visuals and layout for crypto news site.",
      "UX for exploration and engagement.",
      "Responsive layout.",
      "Polished intro experience.",
    ],
    techStack: ["Figma", "Prototyping", "User Research", "Wireframing"],
  },
  {
    title: "Intern",
    company: "Impetus",
    dates: "August 2023 - October 2023",
    description: "As an intern:",
    responsibilities: [
      "Developed 5+ responsive, user-friendly web interfaces.",
      "Increased user engagement metrics by 18%.",
      "Used Git for version control and collaboration.",
      "Resolved merge conflicts 2x faster and improved team productivity.",
      "Built modern UIs with React and Tailwind CSS.",
      "Reduced development time by 25% with utility-first CSS.",
    ],
    responsibilitiesMobile: [
      "5+ responsive web interfaces.",
      "18% higher engagement.",
      "Git and collaboration.",
      "Faster merge resolution, better productivity.",
      "React and Tailwind UIs.",
      "25% faster dev with utility-first CSS.",
    ],
    techStack: ["HTML", "CSS", "JavaScript", "Tailwind", "React", "Git"],
  },
];
